### ISSUE TITLE
Crop out white space in images

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-ucp#1]
This page: http://ucpworkofheart.com/mixed-media.html

Make sure the resolution still doesn't go beyond 300px wide, but just remove the white background that 'borders' each painting on this page. 

Obviously you want to download from FTP first, then clone the gh-pages branch and make sure your FTP version is the same as gh-pages branch, THEN get to work on cropping images and once done, push to gh-pages, merge to master, upload to FTP. 

Due date: Tuesday 6-23-15

**Comment by AaronAguilar** [comment]
Donezo.
