### ISSUE TITLE
Custom 404 page

### ISSUE THREAD

**Issue by purplyrocky** [EditLLC/client-ucp#4]
figure it out

**Comment by purplyrocky** [comment]
@rodneystrong I think i figured out how to do this, do i have permission to create a 404page.html page and add this into the .htaccess file:

ErrorDocument 404 http://www.ucpworkofheart.com/404page.html?

**Comment by rodneystrong** [comment]
nice!

do it. you'll find the. htaccess file in the root of the ftp.

however, do me a favor and create a backup of that file first. how do you
create a backup? all you do is make a copy of the file and then rename the
copy to ". htaccess-backup" and put it in the same place as the original.
htaccess.

then you can edit the htaccess file.

love the initiative you're taking

**Comment by purplyrocky** [comment]
Pretty sure this is done. Does it need to be ftp'd to know for sure? 01a99c42e4d110b0f599dc0cb00a562d63254388

**Comment by purplyrocky** [comment]
nevermind, I ftp'd and it worked :D
